### ISSUE TITLE
sometime regex appears weird

### ISSUE THREAD

**Issue by KimoriTama** [happiness9721/Kirikiri-TPV-JavaScript-TJS#1]
this is a sample.
```javascript
function applyInlineStringVariableExtract(str, context = null, bkslesc = true) {
	str = ((string)str).replace(/&(.*?);/g, function (m) { return "${"+m[1]+"}"; }); // &～; を ${～}に置換
	str = (str + /*sentinel*/'${""}').replace(/(.*?)(\$\{.*?\})/g, function (m) { // ～${～}を検索
		return m[1].replace(this, function (q) { return "\\"+q[0]; }) // ${～}でない部分のクオートなどををエスケープする
			+  m[2]; // ${～}の部分はそのままにする
	} incontextof (bkslesc ? /[\'\\]/g : /[\']/g)); //bkslescでエスケープ対象を決定		
	return ((function(exp){return exp!;}) incontextof context)("@'"+str+"'");
}
```

**Comment by happiness9721** [comment]
Thanks for your reported.

I think it is not a completely a couple of brackets.

I try adding another brackets and it seems work correctly.

<img width="862" alt="截圖 2023-05-31 15 55 59" src="https://github.com/happiness9721/Kirikiri-TPV-JavaScript-TJS/assets/4532358/9133631b-641a-44d2-aac8-60f51741e41e">

**Comment by KimoriTama** [comment]
> Thanks for your reported.
> 
> I think it is not a completely a couple of brackets.
> 
> I try adding another brackets and it seems work correctly.
> 
> <img alt="截圖 2023-05-31 15 55 59" width="862" src="https://user-images.githubusercontent.com/4532358/242202349-9133631b-641a-44d2-aac8-60f51741e41e.png">


原来是台湾人，那就用中文了。
replace的第二个参数是个函数，两个括号一个是上下文的括号，一个是replace函数的括号。
```
str = (str + '${""}').replace(
    /(.*?)(\$\{.*?\})/g,    //第一个参数是一个正则
    function (m) { 
		......
	} incontextof (bkslesc ? /[\'\\]/g : /[\']/g)    // 这里的一个括号是用来表示它的上下文的
);  //最后这个右括号是replace函数的右边界。
```

**Comment by happiness9721** [comment]
0.0.3 已修正
如果有其他問題的話再麻煩回報，感謝
